language: node_js
node_js:
  - "12.13.1"

jobs:
  include:
    - stage: test
      install:
        - "yarn install"
      script:
        - "yarn run test"
    - stage: deploy-dev
      if: branch = dev
      install:
        - "yarn install"
      script:
        - "yarn run build:dev"
      after_success:
        - "export PKG_VERSION=$(cat package.json | grep version | head -1 | awk -F: '{ print $2 }' | sed 's/[\",]//g' | tr -d '[[:space:]]')"
        - git tag
        - if [[ `git tag` =~ $PKG_VERSION ]]; then export RELEASE=flase;else export RELEASE=true;tar -czvf $PKG_VERSION-dev.tar.gz ./dist/*;git tag $PKG_VERSION;fi
        - if [[ $PKG_VERSION =~ \.0$ ]]; then export PRE_RELEASE=false;echo F;else export PRE_RELEASE=true;echo T;fi
        - git tag
        - "echo VERSION: $PKG_VERSION"
        - "echo RELEASE: $RELEASE"
        - "echo PRE_RELEASE: $PRE_RELEASE"
      deploy:
        - provider: releases
          api_key: $GITHUB_TOKEN
          file: $PKG_VERSION-dev.tar.gz
          prerelease: $PRE_RELEASE
          name: $PKG_VERSION
          body: "这是一个开发版本，可能包含严重的缺陷。"
          skip_cleanup: true
          on:
            branch: dev
    - stage: deploy
      if: branch = master
      install:
        - "yarn install"
      script:
        - "yarn run build"
      after_success:
        - "export PKG_VERSION=$(cat package.json | grep version | head -1 | awk -F: '{ print $2 }' | sed 's/[\",]//g' | tr -d '[[:space:]]')"
        - git tag
        - if [[ `git tag` =~ $PKG_VERSION ]]; then export RELEASE=flase;else export RELEASE=true;tar -czvf $PKG_VERSION.tar.gz ./dist/*;git tag $PKG_VERSION;fi
        - if [[ $PKG_VERSION =~ \.0$ ]]; then export PRE_RELEASE=false;echo F;else export PRE_RELEASE=true;echo T;fi
        - git tag
        - "echo VERSION: $PKG_VERSION"
        - "echo RELEASE: $RELEASE"
        - "echo PRE_RELEASE: $PRE_RELEASE"
      deploy:
        - provider: releases
          api_key: $GITHUB_TOKEN
          file: $PKG_VERSION.tar.gz
          prerelease: $PRE_RELEASE
          name: $PKG_VERSION
          body: "![GitHub Releases](https://img.shields.io/github/downloads/Violin9906/my-ime2/$PKG_VERSION/total)"
          skip_cleanup: true
          on:
            branch: master
            condition: $RELEASE == true
