language: node_js
node_js:
  - "12.13.1"

jobs:
  include:
    - stage: test
      install:
        - "yarn install"
      script:
        - "yarn run test"
    - stage: deploy-dev
      if: branch = dev
      install:
        - "yarn install"
      script:
        - "yarn run build:dev"
      after_success:
        - "export PKG_VERSION=$(cat package.json | grep version | head -1 | awk -F: '{ print $2 }' | sed 's/[\",]//g' | tr -d '[[:space:]]')"
        - tar -C ./dist -czvf $PKG_VERSION-dev.tar.gz ./
        - git tag v$PKG_VERSION-$TRAVIS_COMMIT
        - "echo VERSION: $PKG_VERSION"
        - "echo PRE_RELEASE: $PRE_RELEASE"
      deploy:
        - provider: releases
          api_key: $GITHUB_TOKEN
          file: $PKG_VERSION-dev.tar.gz
          prerelease: true
          name: v$PKG_VERSION Develop version
          skip_cleanup: true
          on:
            branch: dev
    - stage: deploy
      if: branch = master
      install:
        - "yarn install"
      script:
        - "yarn run build"
      after_success:
        - "export PKG_VERSION=$(cat package.json | grep version | head -1 | awk -F: '{ print $2 }' | sed 's/[\",]//g' | tr -d '[[:space:]]')"
        - tar -C ./dist -czvf $PKG_VERSION.tar.gz ./
        - if [[ $PKG_VERSION =~ \.0$ ]]; then export PRE_RELEASE=false;echo F;else export PRE_RELEASE=true;echo T;fi
        - git tag v$PKG_VERSION-$TRAVIS_COMMIT
        - "echo VERSION: $PKG_VERSION"
        - "echo PRE_RELEASE: $PRE_RELEASE"
      deploy:
        - provider: releases
          api_key: $GITHUB_TOKEN
          file: $PKG_VERSION.tar.gz
          prerelease: $PRE_RELEASE
          name: v$PKG_VERSION
          body: "![GitHub Releases](https://img.shields.io/github/downloads/Violin9906/my-ime2/$PKG_VERSION/total)"
          skip_cleanup: true
          on:
            branch: master
